language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

# Setup (performed within virtualenv)
install:
  # Install the package from the source distribution:
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)

# Actual tests:
script:
  # we got nothing so far
  - true
